version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1 # zookeeper 식별자
      ZOOKEEPER_CLIENT_PORT: 2181 # 컨테이너 내부 포트
      ZOOKEEPER_TICK_TIME: 2000 # 클러스터 구성시 동기화 주기 (ms)
      ZOOKEEPER_INIT_LIMIT: 5 # zookeeper 타임아웃 제한 회수
      ZOOKEEPER_SYNC_LIMIT: 2 # zookeeper 싱크 제한 횟수
    ports:
      - "22181:2181" # 외부 포트 : 내부 포트
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181' # zookeeper 연결
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092 # 외부 포트 설정
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT # 보안을 위한 프로토콜 매핑
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT # 보안을 위한 프로토콜 매핑
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # 브로커의 토픽 복제 개수
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0 # 카프카 클러스터 초기 리밸런싱 시조인 대기시간 (ms)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper