spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/gamzabit
    username: sa
    password:
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update
      show_sql: true
      format_sql: true
  sql:
    init:
      mode: always

jwt:
  token:
    access-secret: xxx-access-secret
    refresh-secret: xxx-refresh-secret