server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/gamzabit;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update
      show_sql: true
      format_sql: true
  sql:
    init:
      mode: always
  kafka:
    consumer:
      enabled: true
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: group_1

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  token:
    access-secret: xxx-access-secret
    refresh-secret: xxx-refresh-secret